services:
  app:
    container_name: cards-backend
    build: .
    image: card:latest
    ports:
      - '${HOST_PORT}:${PORT}'
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules # Prevent overwriting node_modules
    environment:
      NODE_ENV: development
    command: npm run dev
# docker-compose -p cards up

